---
title: "Lab 4"
author: "Andrew Steinkruger"
format: html
editor: visual
---

```{r preliminaries, warning = FALSE, message = FALSE}

# Packages

library(gstat) 
library(ncf) 
library(plotly) 
library(sp) 
library(tidyverse) 

# Data

data <- "data/geog565_lab4_data.csv" %>% read_csv

```

**1**

```{r 1, echo = FALSE}

# import the dataset
data = read.csv("data/geog565_lab4_data.csv")

# create 2d contour plot in ggplot
v.2D <- plot_ly(data, x = ~long, y = ~lat, z = ~alt,
                type = "contour", 
                contours = list(showlabels = TRUE)
                )
v.2D


# Create 3d plots 
z.3D <- as.matrix(data[,2:4] %>%
                    pivot_wider(names_from = long, values_from = alt) %>% 
                    select(!(lat)) )

v.3D <- plot_ly(z=z.3D) %>% 
  add_surface(contours = list(z = list(show=TRUE, 
                                       usecolormap=TRUE, 
                                       highlightcolor="#ff0000",
                                       project=list(z=TRUE))))

v.3D

```

To work with simple variograms and correlograms, we assume stationarity and isotropy. However, inspecting both plots suggests that the Coast Range declines toward the coast and that watersheds systematically carve the terrain across the region of interest. Both of these patterns could violate assumptions of stationarity and isotropy.
